### PR TITLE
threading + contacts + samples

### PR DESCRIPTION
**Pull request by ErikSom**
Example of threading in action:
https://box2d-v3-threading.netlify.app/?threading=1&pyramidHeight=50
(adjustable url params)

### CODE REVIEW

**Comment by quinton-ashley** [comment]
Wow! Even a pyramid with 60 layers, 1,770 shapes colliding at once, still runs well on my iPhone 11. Amazing work!

**Comment by quinton-ashley** [comment]
On my M1 MacBook Air 2020 it can run a pyramid with 87 layers, 3741 shapes!

I couldn't get it to build though, here is the error:

```bash
[100%] Built target box2d
/opt/homebrew/bin/cmake -E cmake_progress_start /Users/qashto/dev/forks/box2d3-wasm/box2d3-wasm/cmake-build/CMakeFiles 0
TARGET_TYPE is Debug
Building bare WASM
emcc: warning: --oformat=bare/--post-link are experimental and subject to change. [-Wexperimental]
emcc: error: /Users/qashto/dev/forks/box2d3-wasm/box2d3-wasm/cmake-build/_deps/enkits-src/src/TaskScheduler.cpp: No such file or directory ("/Users/qashto/dev/forks/box2d3-wasm/box2d3-wasm/cmake-build/_deps/enkits-src/src/TaskScheduler.cpp" was expected to be an input file, based on the commandline arguments provided)
```

**Comment by ErikSom** [comment]
@quinton-ashley , you first need to build one time with samples on to get enkit, set it here https://github.com/Birch-san/box2d3-wasm/blob/03bd012746630e3cf0ae51f25126c0f6d427fcb6/box2d3-wasm/shell/0_build_makefile.sh#L65 after that run the build script and turn it off again.

**Comment by quinton-ashley** [comment]
@ErikSom Ah nice, thank you!

I'm on macOS so building with Samples fails because wayland support is not available I assume. But then when I turn on samples and run the build again it succeeds!

```zsh
CMake Error at /Users/qashto/dev/forks/box2d3-wasm/box2d3-wasm/cmake-build/_deps/glfw-src/src/CMakeLists.txt:76 (message):
  Failed to find wayland-scanner
```

Once it does the build, I had trouble running the web demo. This is what's in the JS console, which I read means that an https connection or different CORS settings are required. How are you running it locally?

```console
Box2D.simd.mjs:1177 w:0,t:0x000448a0: pthread_create: environment does not support SharedArrayBuffer, pthreads are not available

Box2D.simd.mjs:795 Aborted(native code called abort())
Box2D.simd.mjs:813 Uncaught (in promise) RuntimeError: Aborted(native code called abort())
    at abort (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.mjs:813:11)
    at __abort_js (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.mjs:1944:7)
    at Box2D.simd.bare.wasm.abort (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.wasm:wasm-function[6281]:0x18361f)
    at Box2D.simd.bare.wasm.std::__2::__throw_system_error(int, char const*) (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.wasm:wasm-function[6479]:0x187f06)
    at Box2D.simd.bare.wasm.std::__2::thread::thread<void (&)(enki::ThreadArgs const&), enki::ThreadArgs, void>(void (&)(enki::ThreadArgs const&), enki::ThreadArgs&&) (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.wasm:wasm-function[4769]:0xa2574)
    at Box2D.simd.bare.wasm.enki::TaskScheduler::StartThreads() (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.wasm:wasm-function[4761]:0xa1a43)
    at Box2D.simd.bare.wasm.enki::TaskScheduler::Initialize(enki::TaskSchedulerConfig) (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.wasm:wasm-function[4859]:0xa91ad)
    at Box2D.simd.bare.wasm.Sample::Sample(int) (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.wasm:wasm-function[4343]:0x93218)
    at Box2D.simd.bare.wasm.Sample* emscripten::internal::operator_new<Sample, int>(int&&) (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.wasm:wasm-function[4187]:0x8de97)
    at Box2D.simd.bare.wasm.emscripten::internal::Invoker<emscripten::internal::rvp::take_ownership, Sample*, int&&>::invoke(Sample* (*)(int&&), int) (http://127.0.0.1:5501/box2d3-wasm/build/dist/es/Box2D.simd.wasm:wasm-function[4344]:0x93320)
 ```
 
EDIT: I tried running it with `http-server --cors` and it didn't work.

**Comment by ErikSom** [comment]
You can go into the demo folder and use yarn serve

**Comment by Birch-san** [comment]
looks like we have a working demo, so even if tdying remains that's a good place to merge

**Pull request merged**
